version: '3.3'

services:
  db: 
    image: postgres
    restart: always
    environment: 
      POSTGRES_DB: go_db
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: go_pass
    ports:
      - 5432:5432

  adminer: 
    depends_on: 
      - db
    image: adminer
    restart: always
    ports: 
      - 8888:8080
